config/routes.rb
require 'resque/server'

Rails.application.routes.draw do
  
  mount Resque::Server.new, at: "/resque"
  namespace :users do
    get 'omniauth_callbacks/facebook'
  end
  devise_for :users, :controllers => { omniauth_callbacks: "users/omniauth_callbacks",
                                      sessions: "users/sessions",
                                      registrations: "users/registrations" }

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :images, only: [:index, :show] do
    resources :comments, except: [:index, :edit, :update, :destroy, :show]
    resources :fans, except: [:index, :edit, :update, :show]
  end
  get 'comments' => 'comments#index'

  resources :categories, only: [:index, :destroy] do
    resources :posts, path: '', except: [:edit, :update, :destroy]
    resources :subscribers,  only: [:create, :new, :destroy]
  end

  resource :creators, only: [:create, :new]
  root 'home_pages#index'
  get '/profile', to: 'profile#index'
end

app/models/admin_user.rb
# frozen_string_literal: true

# model for admin user in AA
class AdminUser < ApplicationRecord
  devise  :database_authenticatable,
          :recoverable,
          :rememberable,
          :validatable
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
# frozen_string_literal: true

# model for top lvl categories
class Category < ApplicationRecord
  paginates_per 6
  extend FriendlyId
  friendly_id :title, use: :slugged

  def should_generate_new_friendly_id?
    title_changed?
  end

  def to_s
    title
  end

  has_many :posts, dependent: :destroy
  has_many :images, through: :posts, dependent: :destroy
  has_many :subscribers, dependent: :destroy
  has_one :creator, dependent: :destroy

  validates_numericality_of :posts_count, greater_than_or_equal_to: 0
  validates :title, presence: true, length: { minimum: 2 }
end

app/models/comment.rb
# frozen_string_literal: true

class Comment < ApplicationRecord
  belongs_to :image, counter_cache: true
  belongs_to :user
  validates :body, presence: true, length: { minimum: 1 }
  paginates_per 50
end

app/models/creator.rb
# frozen_string_literal: true

# users owners category
class Creator < ApplicationRecord
  belongs_to :user
  belongs_to :category

  def to_s
    user.name
  end
end

app/models/fan.rb
# frozen_string_literal: true

# model for likes
class Fan < ApplicationRecord
  belongs_to :user
  belongs_to :image, counter_cache: true

  def to_s
    user.name
  end
end

app/models/image.rb
# frozen_string_literal: true

class Image < ApplicationRecord
  paginates_per 20
  has_one :post, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :fans, dependent: :destroy

  ransacker :containing_category,
            formatter: ->(v) { ids = Post.where(category_id: v).pluck(:image_id);
                              ids.present? ? ids : nil
                              } do |image|
    image.table[:id]
  end

  mount_uploader :image, ImageUploader

  validates_numericality_of :comments_count, greater_than_or_equal_to: 0
  validates_numericality_of :fans_count, greater_than_or_equal_to: 0
  validates :title, presence: true, length: { minimum: 2 }
  validates :image, presence: true, file_size: { less_than_or_equal_to: 50.megabytes }
end

app/models/image_parser.rb
# frozen_string_literal: true

# model for save url image from other site
class ImageParser < ApplicationRecord
  validates :image_url, presence: true
end

app/models/post.rb
# frozen_string_literal: true

# model for connections categories with images
class Post < ApplicationRecord
  paginates_per 5
  after_create :new_image_in_subscribes_email

  belongs_to :image, dependent: :destroy
  belongs_to :category, counter_cache: true

  def to_s
    image.title
  end

  validates :image_id, presence: true
  validates :category_id, presence: true

  private

  def new_image_in_subscribes_email
    Resque.enqueue(NewImageSubscribedEmailJob, category) unless Rails.env.test?
  end
end

app/models/subscriber.rb
# frozen_string_literal: true

# modell for saving subscrscribes
class Subscriber < ApplicationRecord
  after_create :send_subscribed_email

  belongs_to :category
  belongs_to :user

  validates_uniqueness_of :user_id, scope: :category_id

  def to_s
    user.name
  end

  private

  def send_subscribed_email
    Resque.enqueue(SubscribedEmailJob, user, category) unless Rails.env.test?
  end
end

app/models/user.rb
# frozen_string_literal: true

# model for users from devise
class User < ApplicationRecord
  after_create :send_welcome_email
  mount_uploader :avatar, ImageUploader

  has_many :comments, dependent: :destroy
  has_many :subscribers, dependent: :destroy
  has_many :creators, dependent: :destroy
  has_many :fans, dependent: :destroy
  has_many :user_actions, dependent: :destroy
  def self.logins_before_captcha
    2
  end

  def self.find_for_facebook_oauth access_token
    if user = User.where(email: access_token.extra.raw_info.email).first
      user
    else
      User.create!(name: access_token.extra.raw_info.name,
                    email: access_token.extra.raw_info.email,
                    confirmed_at: Time.now,
                    avatar: access_token.extra.raw_info.avatar,
                    password: Devise.friendly_token[0, 20])
    end
  end
  devise :database_authenticatable,
        :registerable,
        :recoverable,
        :rememberable,
        :trackable,
        :validatable,
        :omniauthable,
        :confirmable

  private

  def send_welcome_email
    user = self
    Resque.enqueue(WelcomeEmailJob, user)
    # UserMailer.welcome_email(self).deliver
  end
end

app/models/user_action.rb
# frozen_string_literal: true

# modell for writing user actions
class UserAction < ApplicationRecord
  belongs_to :user
  validates :user_id, presence: true
  validates :action, presence: true
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def new
    @post = Post.new
  end

  def create
    @category = Category.find(params[:category_id])
    @image = Image.new(image_params)
    if @image.save
      @category.posts.create(category: @category, image: @image)
      redirect_to category_posts_path(@category)
    else
      render :new
    end
  end

  def index
    @category = Category.find(params[:category_id])
    @posts = @category.posts.order('created_at DESC').page(params[:page])
    @images = Image.order(:title).page params[:page]
    @images = {}
    @states = {}
    @posts.each do |post|
      @images[post] = post.image if post
    end
  end

  def show
    @category = Category.friendly.find(params[:category_id])
    @post = @category.posts.find(params[:id])
    @image = @post.image
  end

  private

  def image_params
    params.require(:image).permit(:title, :image)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/categories_helper.rb
# frozen_string_literal: true

module CategoriesHelper
end

app/helpers/comments_helper.rb
# frozen_string_literal: true

module CommentsHelper
  def author(user_id)
    User.find(user_id).name
  end
end

app/helpers/creators_helper.rb
# frozen_string_literal: true

module CreatorsHelper
end

app/helpers/fans_helper.rb
# frozen_string_literal: true

module FansHelper
  def pre_like
    @image.fans.find { |fan| fan.user_id == current_user.id }
  end
end

app/helpers/home_pages_helper.rb
# frozen_string_literal: true

module HomePagesHelper
end

app/helpers/images_helper.rb
# frozen_string_literal: true

module ImagesHelper
end

app/helpers/posts_helper.rb
# frozen_string_literal: true

module PostsHelper
end

app/helpers/profile_helper.rb
# frozen_string_literal: true

module ProfileHelper
end

app/helpers/subscribers_helper.rb
# frozen_string_literal: true

module SubscribersHelper
end

app/views/posts/_errors.html.haml
- if object.errors.any?
  %h3 Some errors were found:
  %ul
    - object.errors.full_messages.each do |message|
      %li= message

app/views/posts/create.html.haml
%h2 Add a post:
= render 'errors'
= form_with(model: [ @category, @category.posts.build ], local: true) do |form|
  %p
    = form.label :Title
    %br/
    = form.text_field :Title
  %p
    = form.label :body
    %br/
    = form.text_area :body
    = form.hidden :image_cash
  %p
    = form.submit

app/views/posts/edit.html.haml
%h1 Edit post
= form_with scope: :post, url: category_posts_path, local: true do |form|
  %div
    = form.label :title
    %br/
    = form.text_field :title
  %div
    = form.label :Body
    %br/
    = form.text_area :body
  %div
    = form.label :image
    = form.file_field :image
  = form.submit

app/views/posts/index.html.haml
.container
  %h1= @category.title.capitalize
  .all-posts
    - @posts.each do |post|
      .post
        .title
          = link_to category_post_path(@category, post) do
            %h2= @images[post].title.capitalize
          = link_to category_post_path(@category, post) do
            .post-image
              = image_tag(@images[post].image.medium_thumb.url,
              alt: 'Image', class: 'img-fluid img-thumbnail ')
              .post-substrate
                .reviev
                  %span.glyphicon.glyphicon-eye-open
                .state
                  %p
                    %span
                      = @images[post].comments_count
                    %span.glyphicon.glyphicon-comment
                  %p
                    %span
                      = @images[post].fans_count
                    %span.glyphicon.glyphicon-heart
  = link_to t('posts.new_post'), new_category_post_path(), class:"addImage-button" if user_signed_in?
  = paginate @posts, outer_window: 3

app/views/posts/new.html.haml
.container
  %h2= t('posts.add_post')
  = form_with scope: :image, url: category_posts_path, local: true do |form|
    %p
      = form.label t('images.name')
      %br/
      = form.text_field :title, class: "form-control"
    %p
      = form.label t('images.image')
      %br/
      = form.file_field :image
      = form.hidden_field :image_cache
    %p
      = form.submit

app/views/posts/show.html.haml
.container
  %h2
    = @image.title.capitalize
  .image
    = image_tag(@image.image.url, alt: 'Image', class:"img-fluid img-thumbnail")
  = render 'fans/likes', image: @image
  = render 'comments/comment', image: @image
  = render 'comments/form', image: @image if user_signed_in?